name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    environment: prd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          yarn ci

      - name: Linting
        run: |
          npx svelte-check

      - name: Build sources
        run: |
          yarn run build

      - name: Build sources
        run: |
          yarn install -g vercel
          cd public
          vercel deploy --name winalot